### ISSUE TITLE
Toolchain fixes - Update for Angular 4

### ISSUE THREAD

**Issue by SethDavenport** [angular-redux/form#5]
Tests recently started failing with this stack trace:

`yarn test`:

```
ERROR in ./source/tests.entry.ts
Module build failed: TypeError: Cannot set property 'babelOptions' of undefined
    at Object.ngcLoader (/Users/sdavenpo/code/angular-redux/ng2-redux-form/node_modules/@ngtools/webpack/src/loader.js:200:34)
28 01 2017 22:45:11.188:ERROR [karma]: { Error: no such file or directory
    at MemoryFileSystem.readFileSync (/Users/sdavenpo/code/angular-redux/ng2-redux-form/node_modules/memory-fs/lib/MemoryFileSystem.js:107:10)
    at MemoryFileSystem.(anonymous function) [as readFile] (/Users/sdavenpo/code/angular-redux/ng2-redux-form/node_modules/memory-fs/lib/MemoryFileSystem.js:300:34)
    at doRead (/Users/sdavenpo/code/angular-redux/ng2-redux-form/node_modules/karma-webpack/lib/karma-webpack.js:201:29)
    at Plugin.readFile (/Users/sdavenpo/code/angular-redux/ng2-redux-form/node_modules/karma-webpack/lib/karma-webpack.js:205:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  code: 'ENOENT',
```

**Comment by SethDavenport** [comment]
Also, can't run the example: webpack fails with `ERROR in Could not resolve "./module" from "./module"`

**Comment by SethDavenport** [comment]
Actually this toolchain is diverging sharply from later angular releases, which is making it increasingly hard to maintain.  @clbond @e-schultz let's see if we can simplify.

**Comment by SethDavenport** [comment]
Specific items:
* [ ] unit tests no longer run
* [x] example app no longer builds
* [x] chai has typing problems that leak out of the package and into projects trying to use it - this burned us in `store` as well. Need to switch to Jasmine and TestBed, etc.
* [x] too many things in deps instead of devDeps; this affects consumers
* [x] no prepublish step
* [x] not sure `npm run build` needs to be a postinstall step: shouldn't we publish prebuilt files to npm instead?
* [x] references in source code for `@angular/**/src/**` are mostly broken with Angular 4. Can we do this without referencing Angular's private internals?

**Comment by clbond** [comment]
I honestly am not sure it's worth the effort to maintain this library. As far as I know nobody is really using it. @SethDavenport

**Comment by SethDavenport** [comment]
Updated to work with angular 4: angular-redux/form@6.1.1 released with these fixes.
